const express = require('express')
const router = express.Router()
const home = require('./modules/home')
const record = require('./modules/record')
const user = require('./modules/user')
const auth = require('./modules/auth')
router.use('/expenses', record)
router.use('/auth', auth)
router.use('/users', user)
router.use('/', home)
module.exports = router